/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_002;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Guerrero
 */
public class INTERFAZ_CUENTA extends javax.swing.JFrame {
    public static int cuenta;
    public static int NIP;

    
    /**
     * Creates new form INTERFAZ_CLAVE
     */
    public INTERFAZ_CUENTA() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        txt_numCuenta.requestFocus();
        jLabel1.setText(" ");
        jLabel2.setText(" ");
        jLabel3.setText(" ");
        jLabel4.setText(" ");
        jLabel5.setText(" ");
        jLabel6.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_titulo = new javax.swing.JLabel();
        label_ranura = new javax.swing.JLabel();
        jButton_ranura = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Confirmar = new javax.swing.JButton();
        jLabel_bienvenido = new javax.swing.JLabel();
        txt_numCuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_CargarDatos = new javax.swing.JButton();
        btn_Finalizar = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fondo_titulo = new javax.swing.JLabel();
        pantalla = new javax.swing.JLabel();
        fondo_teclado = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_titulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setText("jLabel1");
        getContentPane().add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 250, 20));

        label_ranura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_ranura.setForeground(new java.awt.Color(0, 204, 0));
        label_ranura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ranura.setText("RANURA");
        getContentPane().add(label_ranura, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));
        getContentPane().add(jButton_ranura, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 220, 30));

        btn1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(39, 21));
        btn1.setMinimumSize(new java.awt.Dimension(39, 21));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 40, 30));

        btn2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(39, 21));
        btn2.setMinimumSize(new java.awt.Dimension(39, 21));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 40, 30));

        btn3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(39, 21));
        btn3.setMinimumSize(new java.awt.Dimension(39, 21));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 40, 30));

        btn4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn4.setText("4");
        btn4.setMaximumSize(new java.awt.Dimension(39, 21));
        btn4.setMinimumSize(new java.awt.Dimension(39, 21));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 40, 30));

        btn5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(39, 21));
        btn5.setMinimumSize(new java.awt.Dimension(39, 21));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 40, 30));

        btn6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(39, 21));
        btn6.setMinimumSize(new java.awt.Dimension(39, 21));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 40, 30));

        btn7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(39, 21));
        btn7.setMinimumSize(new java.awt.Dimension(39, 21));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 40, 30));

        btn8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(39, 21));
        btn8.setMinimumSize(new java.awt.Dimension(39, 21));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 40, 30));

        btn9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(39, 21));
        btn9.setMinimumSize(new java.awt.Dimension(39, 21));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 40, 30));

        btn_delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_delete.setText("X");
        btn_delete.setMaximumSize(new java.awt.Dimension(39, 21));
        btn_delete.setMinimumSize(new java.awt.Dimension(39, 21));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 110, 40));

        btn0.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(39, 21));
        btn0.setMinimumSize(new java.awt.Dimension(39, 21));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 40, 30));

        btn_Cancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Cancelar.setText("CANCELAR");
        btn_Cancelar.setMaximumSize(new java.awt.Dimension(39, 21));
        btn_Cancelar.setMinimumSize(new java.awt.Dimension(39, 21));
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 110, 40));

        btn_Confirmar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Confirmar.setText("CONFIRMAR");
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 110, 40));

        jLabel_bienvenido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_bienvenido.setForeground(new java.awt.Color(0, 204, 51));
        jLabel_bienvenido.setText("BIENVENIDO ESTIMADO USUARIO");
        getContentPane().add(jLabel_bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 20));

        txt_numCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numCuentaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_numCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 240, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 51));
        jLabel9.setText("INGRESA EL NUMERO DE CUENTA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 20));

        btn_CargarDatos.setText("CARGAR");
        getContentPane().add(btn_CargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        btn_Finalizar.setText("FINALIZAR");
        btn_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, -1, -1));

        mensaje.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mensaje.setText("mensaje");
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 290, 90));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 50));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 50));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, 50));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 80, 50));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 80, 50));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 80, 50));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 20));

        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 20));

        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, 20));

        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, 20));

        jLabel5.setText("jLabel1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, 20));

        jLabel6.setText("jLabel1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, 20));
        getContentPane().add(fondo_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 890, 60));
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 630, 380));

        fondo_teclado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(fondo_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 630, 180));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        // TODO add your handling code here:    
      
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void txt_numCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numCuentaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_numCuentaKeyTyped

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        this.txt_numCuenta.setText(this.txt_numCuenta.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (txt_numCuenta.getText().length() != 0) {
            txt_numCuenta.setText(txt_numCuenta.getText().substring(0, txt_numCuenta.getText().length() - 1));
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinalizarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_FinalizarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        txt_numCuenta.setText("");
        mensaje.setText("");
        jLabel9.setText("INGRESA EL NUMERO DE CUENTA:");
    }//GEN-LAST:event_btn_CancelarActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_CUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_CUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_CUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_CUENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFAZ_CUENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_CargarDatos;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JButton btn_Finalizar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo_teclado;
    private javax.swing.JLabel fondo_titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_ranura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_bienvenido;
    private javax.swing.JLabel label_ranura;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel pantalla;
    private javax.swing.JTextField txt_numCuenta;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
